apiVersion: v1
kind: Secret
metadata:
  name: powerverse-secrets
type: Opaque
stringData:
  database-url: postgresql+asyncpg://postgres:CHANGE_ME@powerverse-postgres:5432/powerverse
  postgres-password: CHANGE_ME
  secret-key: CHANGE_ME_WITH_RANDOM_SECRET_KEY